spring.application.name=rate-provider
spring.main.banner-mode=off
server.port=${PROVIDER_PORT:8091}
discovery.address=${ZOOKEEPER_ADDRESS:localhost:42181}
discovery.path=/services/currency
logging.level.org.apache.zookeeper=WARN
logging.level.org.apache.curator=WARN
discovery.host=${PROVIDER_HOST:localhost}
