spring.application.name=rate-printer
spring.main.banner-mode=off
server.port=${PRINTER_PORT:8096}
discovery.address=${ZOOKEEPER_ADDRESS:localhost:52181}
discovery.path=/services/currency
logging.level.org.apache.zookeeper=WARN
logging.level.org.apache.curator=WARN
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.minimum-expected-value.http.server.requests=1us
management.metrics.distribution.maximum-expected-value.http.server.requests=10s
client.id=${CLIENT_ID:rate-printer}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
